starting_population=10000 # business owners will be added to this

no_education={ chance=10, salary_range={min=15000, max=22000} }
high_school_diploma={ chance=28, salary_range={min=28000, max=40000} }
college={ chance=16, salary_range={min=50000, max=60000} }
associate_degree={ chance=10, salary_range={min=40000, max=70000} }
bachelors={ chance=30, salary_range={min=60000, max=90000} }
advanced_degree={ chance=6, salary_range={min=100000, max=300000} }